### ISSUE TITLE
Failed to install in Ubuntu

### ISSUE THREAD

**Issue by reymonera** [Stephane-S/Simplot_PlusPlus#3]
Hi,

SimPlot++ is great and exactly what I was looking for. So thanks for the tool.

However, I found an error while installing it on my Ubuntu machine with the `bokeh` package. Apparently I have it installed, although I remember that, while installing the libraries, an error occured. And, when I tried to use the software, this appeared:

```
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    from lib.Network.network_analysis import NetworkAnalysis
  File "/home/lgm/Documents/bb_ccastillo/Simplot_PlusPlus-master/lib/Network/network_analysis.py", line 3, in <module>
    from lib.Network.Bokeh_graph_functions import get_color_palette_dicts
  File "/home/lgm/Documents/bb_ccastillo/Simplot_PlusPlus-master/lib/Network/Bokeh_graph_functions.py", line 1, in <module>
    from bokeh import plotting, embed, resources
  File "/home/lgm/Documents/bb_ccastillo/Simplot_PlusPlus-master/SimPlot++_env/lib/python3.8/site-packages/bokeh/plotting/__init__.py", line 67, in <module>
    from ..document import Document; Document
  File "/home/lgm/Documents/bb_ccastillo/Simplot_PlusPlus-master/SimPlot++_env/lib/python3.8/site-packages/bokeh/document/__init__.py", line 35, in <module>
    from .document import DEFAULT_TITLE ; DEFAULT_TITLE
  File "/home/lgm/Documents/bb_ccastillo/Simplot_PlusPlus-master/SimPlot++_env/lib/python3.8/site-packages/bokeh/document/document.py", line 49, in <module>
    from ..core.templates import FILE
  File "/home/lgm/Documents/bb_ccastillo/Simplot_PlusPlus-master/SimPlot++_env/lib/python3.8/site-packages/bokeh/core/templates.py", line 42, in <module>
    from jinja2 import Environment, FileSystemLoader, Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/home/lgm/Documents/bb_ccastillo/Simplot_PlusPlus-master/SimPlot++_env/lib/python3.8/site-packages/jinja2/__init__.py)
```

This is the info of my computer:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```
Thanks for any answer you could give me.

Regards,

Camila C.

P.S: I was wondering about the use of SimPlots for complete genome comparisons. Is it common? I want to compare small, bacterial genomes (less than 2 Mb) but most of the work done with SimPlots is with viruses and fragments.

**Comment by Stephane-S** [comment]
Hi,

Thank you for your interest in SimPlot++!

It does indeed look like your issue is with the package installation. I'd suggest creating a clean virtual environment (https://docs.python.org/3/library/venv.html) and using the requirment.txt file on the [github](https://github.com/Stephane-S/Simplot_PlusPlus) to install the dependencies. The detailed instructions are available [here](https://github.com/Stephane-S/Simplot_PlusPlus/wiki/Installation-guide). It might not fix the problem but at the very least it will eliminate risks of conflicts with other installed packages and you'll be able to better see what errors pop up. 

As for complete genome comparison, it is possible to do whole genome comparisons but depending on the size of the dataset, it might take a long time or encounter memory issues. If it fails, I'd suggest splitting the genome in multiple regions of interest such as genes and test them separately.

I hope this help and let me know if you have more issues
Stephane S.

**Comment by reymonera** [comment]
Hi,

Thanks for the input. I'm still having some issues with the installation on an Ubuntu computer, but I will try later.

However, I tried to elaborate a SimPlot in a Windows machine for a comparison between several genomes with an average size of ~1.5 Mb and I've noticed that in the plot, after a determined point, a lot of genomes stop being drawn, while 5 others continue in the plot. Would this be a memory problem then as you described?

Thanks for the help!

**Comment by ybendana** [comment]
I had to add these specs to get it to build in Linux: 

`jinja2 = "<3"`
`markupsafe = "<2.1.0"`
